version: "3.9"
services:
  server:
    container_name: rsvst
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
    - "8100:8100"

  database:
    container_name: postgres_rsvst
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_rsvst
    env_file: .env
    depends_on:
      - database
    ports:
      - "8081:8081"
    restart: always
  
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

volumes:
  data:
